server:
    port: 8080
    tomcat:
        uri-encoding: utf-8
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/t_shop?useUnicode=true&characterEncoding=UTF-8
        username: root
        password:  Meng3220175 #Meng3220175.  #mac 990213 # windows
        # 初始化大小，最小，最大
        initialSize: 1
        minIdle: 3
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        filters: stat,wall,slf4j
    thymeleaf:
        cache: false
        mode: LEGACYHTML5
    mvc:
        static-path-pattern: /static/**
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
mybatis:
    type-aliases-package: com.mty.shop.model
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
# 分页配置
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
mapper:
    mappers: com.mty.shop.util.MyMapper
    not-empty: false
    identity: MYSQL

uploadDir: C:\Users\1\Desktop\新建文件夹 (2)\seaFood-Shop\seaFood-Shop