server:
    port: 8080
    tomcat:
        uri-encoding: utf-8
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/t_shop?useUnicode=true&characterEncoding=UTF-8
        username: root
        password:  Meng3220175.  #mac 990213 # windows Meng3220175
        # Initialize size, min, max
        initialSize: 1
        minIdle: 3
        maxActive: 20
        # Configure the time for getting a connection to wait for timeout
        maxWait: 60000
        filters: stat,wall,slf4j
    thymeleaf:
        cache: false
        mode: LEGACYHTML5
    mvc:
        static-path-pattern: /static/**
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
mybatis:
    type-aliases-package: com.mty.shop.model
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
# Paging configuration
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
mapper:
    mappers: com.mty.shop.util.MyMapper
    not-empty: false
    identity: MYSQL

uploadDir: /Users/mwh/Desktop/seafood shop/seaFood-Shop/upload